# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: cleanly install dependencies
          command: if [ -d node_modules ]; then rm -rf node_modules; fi; npm install

      - run: npm test
